cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "rwhogg/bob"
tap "rhoggSugarcrm/versions"

brew "browser"
brew "codemod"
brew "composer"
brew "coreutils"
brew "curl"
brew "dark-mode"
brew "diff-so-fancy"
brew "dos2unix"
brew "dtrx"
brew "duti"
brew "editorconfig"
brew "emojify"
brew "gist"
brew "git"
brew "git-extras"
brew "gnu-sed"
brew "grep"
brew "grip"
# brew "grunt-cli"
brew "hub"
brew "ispell"
# brew "jsonlint"
brew "less"
brew "make"
brew "micro"
brew "moz-git-tools"
brew "multitail"
brew "nmap"
brew "node@8"
brew "openssl"
brew "p7zip"
brew "rename"
brew "rhoggSugarcrm/versions/php71"
brew "rhoggSugarcrm/bob/bobs-git-utils"
brew "rhoggSugarcrm/bob/small-scripts"
brew "the_silver_searcher"
brew "vnu"
brew "wget"
brew "willgit"
brew "zzz"
cask "atom"
cask "caffeine"
cask "docker-toolbox"
cask "firefox"
cask "font-ubuntu"
cask "forklift" # the only non-awful Mac file manager I've ever found
cask "gimp"
# cask "github-desktop"
cask "iterm2"
cask "java"
cask "keepassxc"
cask "mysqlworkbench"
cask "phpstorm"
cask "spectacle"
